services:
  floci:
    image: floci/floci:latest
    container_name: floci
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./floci-data:/app/data
    environment:
      - FLOCI_DEFAULT_REGION=us-east-1
      - FLOCI_HOSTNAME=localhost
      - DEBUG=1
    networks:
      - floci-net

networks:
  floci-net:
    driver: bridge

volumes:
  floci-data:
